# Generated by Django 3.1.4 on 2021-01-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habixuser',
            name='uuid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
