# Generated by Django 3.1.4 on 2021-01-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210103_0424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyTasks',
            new_name='DailyTask',
        ),
    ]
